name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install Playwright Chromium
        run: pnpm playwright install chromium
        working-directory: tests

      - name: Test unit
        run: pnpm test:unit

      - name: Test e2e dev
        run: pnpm test:dev
        working-directory: tests

      - name: Test e2e build
        run: pnpm test:build
        working-directory: tests

      - name: Archive test results
        if: failure()
        run: tar -czf test-results.tar.gz tests/test-results

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          retention-days: 3
          name: test-failure-${{ github.run_id }}
          path: test-results.tar.gz
